<a href="https://colab.research.google.com/github/KhalPrawira/Big-Data_Assignment/blob/main/UAS/Code/elt_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Cell 1
import os
import requests
import pandas as pd
import time
from datetime import datetime
from sqlalchemy import create_engine, text
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
# Cell 2
print("⚙️ [SETUP] Mempersiapkan Environment...")

folders = ["datalake", "logs", "elt_pipeline", "warehouse"]
for f in folders:
    os.makedirs(f, exist_ok=True)
    print(f"   ✅ Folder '{f}/' siap.")

os.system("sudo apt-get -y -qq update > /dev/null")
os.system("sudo apt-get -y -qq install postgresql > /dev/null")
os.system("sudo service postgresql start")

os.system('sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD \'bigdata\';" > /dev/null')
os.system('sudo -u postgres psql -U postgres -c "DROP DATABASE IF EXISTS ecommerce_db;" > /dev/null')
os.system('sudo -u postgres psql -U postgres -c "CREATE DATABASE ecommerce_db;" > /dev/null')

print("✅ Database PostgreSQL berhasil di-reset & dijalankan.")

⚙️ [SETUP] Mempersiapkan Environment...
   ✅ Folder 'datalake/' siap.
   ✅ Folder 'logs/' siap.
   ✅ Folder 'elt_pipeline/' siap.
   ✅ Folder 'warehouse/' siap.
✅ Database PostgreSQL berhasil di-reset & dijalankan.

In [3]:
# Cell 3
def write_extract_log(source_name, rows, cols, size_mb, exec_time):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = (f"[{timestamp}] [EXTRACT] SOURCE: {source_name} | "
                 f"DIM: {rows} rows x {cols} cols | "
                 f"SIZE: {size_mb:.2f} MB | TIME: {exec_time:.2f}s")

    print(log_entry)

    with open("logs/extract_log.txt", "a") as f:
        f.write(log_entry + "\n")

# **Extract**

In [4]:
# Cell 4
def extract_etl_source1():
    """
    Mengambil Dataset E-Commerce.
    ATURAN: Tidak boleh ada cleaning. Simpan stream langsung ke file.
    """
    url = "https://github.com/KhalPrawira/Big-Data_Assignment/raw/refs/heads/main/UAS/Dataset/Pakistans%20Largest%20E-Commerce%20Dataset.csv"
    save_path = "datalake/raw_ecommerce.csv"
    source_name = "Source 1 (E-Commerce)"

    print(f"\n⬇️ Sedang mengunduh {source_name}...")
    start_time = time.time()

    try:
        with requests.get(url, stream=True) as r:
            r.raise_for_status()
            with open(save_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)

        file_size = os.path.getsize(save_path) / (1024 * 1024)

        df_meta = pd.read_csv(save_path, low_memory=False, on_bad_lines='skip')
        rows, cols = df_meta.shape

        write_extract_log(source_name, rows, cols, file_size, time.time() - start_time)
        return True

    except Exception as e:
        print(f"❌ Gagal Extract {source_name}: {e}")
        return False

In [5]:
# Cell 5
def extract_etl_source2():
    """
    Mengambil Dataset Holidays.
    """
    url = "https://github.com/KhalPrawira/Big-Data_Assignment/raw/refs/heads/main/UAS/Dataset/pakistan_holiday.csv"
    save_path = "datalake/raw_holidays.csv"
    source_name = "Source 2 (Holidays)"

    print(f"⬇️ Sedang mengunduh {source_name}...")
    start_time = time.time()

    try:
        response = requests.get(url)
        with open(save_path, 'wb') as f:
            f.write(response.content)

        df_meta = pd.read_csv(save_path)
        file_size = os.path.getsize(save_path) / (1024 * 1024)

        write_extract_log(source_name, df_meta.shape[0], df_meta.shape[1], file_size, time.time() - start_time)
        return True
    except Exception as e:
        print(f"❌ Gagal Extract {source_name}: {e}")
        return False

In [6]:
# Cell 6
if __name__ == "__main__":
    if os.path.exists("logs/extract_log.txt"):
        os.remove("logs/extract_log.txt")

    success_1 = extract_etl_source1()
    success_2 = extract_etl_source2()

    if success_1 and success_2:
        print("\n✅ PART 1 (EXTRACT) SELESAI.")
        print("📁 Cek folder 'datalake/' di panel kiri. Harus ada 2 file CSV.")
    else:
        print("\n❌ ADA KEGAGALAN SAAT EXTRACT.")

⬇️ Sedang mengunduh Source 1 (E-Commerce)...
[2026-01-04 15:43:20] [EXTRACT] SOURCE: Source 1 (E-Commerce) | DIM: 1153432 rows x 26 cols | SIZE: 119.94 MB | TIME: 6.16s
⬇️ Sedang mengunduh Source 2 (Holidays)...
[2026-01-04 15:43:20] [EXTRACT] SOURCE: Source 2 (Holidays) | DIM: 60 rows x 5 cols | SIZE: 0.00 MB | TIME: 0.41s

✅ PART 1 (EXTRACT) SELESAI.
📁 Cek folder 'datalake/' di panel kiri. Harus ada 2 file CSV.

# Load

In [7]:
# Cell 7
os.system("sudo service postgresql start > /dev/null")
engine = create_engine('postgresql://postgres:bigdata@localhost:5432/ecommerce_db', echo=False)

def write_load_log(table_name, rows, cols, status, exec_time):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = (f"[{timestamp}] [LOAD] TABLE: {table_name} | "
                 f"STATUS: {status} | DIM: {rows}x{cols} | TIME: {exec_time:.2f}s")

    print(log_entry)
    with open("logs/load_log.txt", "a") as f:
        f.write(log_entry + "\n")

In [8]:
# Cell 8
def load_raw_layer_dynamic():
    print("\n🚀 [LOAD] Memulai Ingestion ke Raw Layer...")

    with engine.connect() as conn:
        conn.execute(text("CREATE SCHEMA IF NOT EXISTS raw_layer;"))
        conn.commit()

    tasks = [
        ("raw_layer.ecommerce", "datalake/raw_ecommerce.csv"),
        ("raw_layer.holidays", "datalake/raw_holidays.csv")
    ]

    for table_name, csv_path in tasks:
        t0 = time.time()
        try:
            print(f"   ...Processing {csv_path}")

            df_iter = pd.read_csv(csv_path, dtype=str, on_bad_lines='skip', chunksize=5000)

            df_sample = next(df_iter)

            raw_columns = df_sample.columns
            clean_columns = [
                c.strip().lower()
                .replace(' ', '_')
                .replace('-', '_')
                .replace('.', '')
                .replace(':', '_')
                for c in raw_columns
            ]

            cols_ddl = ", ".join([f'"{col}" TEXT' for col in clean_columns])
            create_query = f"DROP TABLE IF EXISTS {table_name}; CREATE TABLE {table_name} ({cols_ddl});"

            with engine.connect() as conn:
                conn.execute(text(create_query))
                conn.commit()

            df_full_iter = pd.read_csv(csv_path, dtype=str, on_bad_lines='skip', chunksize=5000)

            total_rows = 0
            for chunk in df_full_iter:
                chunk.columns = clean_columns
                chunk.to_sql(table_name.split('.')[1], engine, schema='raw_layer',
                             if_exists='append', index=False)
                total_rows += len(chunk)

            write_load_log(table_name, total_rows, len(clean_columns), "SUCCESS", time.time() - t0)

        except Exception as e:
            print(f"❌ Gagal Load {table_name}: {e}")
            write_load_log(table_name, 0, 0, f"FAILED: {str(e)}", 0)

if __name__ == "__main__":
    if os.path.exists("logs/load_log.txt"):
        os.remove("logs/load_log.txt")

    load_raw_layer_dynamic()

🚀 [LOAD] Memulai Ingestion ke Raw Layer...
   ...Processing datalake/raw_ecommerce.csv
[2026-01-04 15:45:29] [LOAD] TABLE: raw_layer.ecommerce | STATUS: SUCCESS | DIM: 1153432x26 | TIME: 128.18s
   ...Processing datalake/raw_holidays.csv
[2026-01-04 15:45:29] [LOAD] TABLE: raw_layer.holidays | STATUS: SUCCESS | DIM: 60x5 | TIME: 0.02s

In [9]:
# Cell 9
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

import os
os.system("sudo service postgresql start > /dev/null")
engine = create_engine('postgresql://postgres:bigdata@localhost:5432/ecommerce_db', echo=False)

def inspect_raw_database():
    print("🕵️‍♂️ INSPEKSI DATA RAW (PRE-TRANSFORM CHECK)...\n")

    tables = [
        ("raw_layer.ecommerce", "Tabel Utama Transaksi"),
        ("raw_layer.holidays", "Tabel Hari Libur")
    ]

    for table_name, desc in tables:
        print(f"📂 {desc} ({table_name})")

        try:
            count_query = f"SELECT COUNT(*) FROM {table_name}"
            total_rows = pd.read_sql(count_query, engine).iloc[0,0]

            data_query = f"SELECT * FROM {table_name} LIMIT 5"
            df_preview = pd.read_sql(data_query, engine)
            total_cols = len(df_preview.columns)

            print(f"📊 STATISTIK DIMENSI:")
            print(f"   • Jumlah Baris : {total_rows}")
            print(f"   • Jumlah Kolom : {total_cols}")

            print(f"\n📋 DAFTAR SEMUA FITUR (KOLOM):")
            col_list = list(df_preview.columns)
            print(f"   {col_list}")

            print(f"\n👀 PREVIEW DATA (5 Baris Teratas):")
            display(df_preview)
            print("\n")

        except Exception as e:
            print(f"❌ Error membaca tabel {table_name}: {e}\n")

inspect_raw_database()

🕵️‍♂️ INSPEKSI DATA RAW (PRE-TRANSFORM CHECK)...

📂 Tabel Utama Transaksi (raw_layer.ecommerce)
📊 STATISTIK DIMENSI:
   • Jumlah Baris : 1153432
   • Jumlah Kolom : 26

📋 DAFTAR SEMUA FITUR (KOLOM):
   ['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered', 'grand_total', 'increment_id', 'category_name_1', 'sales_commission_code', 'discount_amount', 'payment_method', 'working_date', 'bi_status', 'mv', 'year', 'month', 'customer_since', 'm_y', 'fy', 'customer_id', 'unnamed__21', 'unnamed__22', 'unnamed__23', 'unnamed__24', 'unnamed__25']

👀 PREVIEW DATA (5 Baris Teratas):

    item_id          status created_at                                                sku   price qty_ordered grand_total increment_id    category_name_1 sales_commission_code discount_amount payment_method working_date bi_status       mv    year month customer_since     m_y    fy customer_id unnamed__21 unnamed__22 unnamed__23 unnamed__24 unnamed__25
0  211131.0        complete   7/1/2016                                  kreations_YI 06-L  1950.0         1.0      1950.0    100147443    Women's Fashion                    \N             0.0            cod     7/1/2016     #REF!   1,950   2016.0   7.0         2016-7  7-2016  FY17         1.0        None        None        None        None        None
1  211133.0        canceled   7/1/2016  kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...   240.0         1.0       240.0    100147444  Beauty & Grooming                    \N             0.0            cod     7/1/2016     Gross     240   2016.0   7.0         2016-7  7-2016  FY17         2.0        None        None        None        None        None
2  211134.0        canceled   7/1/2016                                 Ego_UP0017-999-MR0  2450.0         1.0      2450.0    100147445    Women's Fashion                    \N             0.0            cod     7/1/2016     Gross   2,450   2016.0   7.0         2016-7  7-2016  FY17         3.0        None        None        None        None        None
3  211135.0        complete   7/1/2016                                     kcc_krone deal   360.0         1.0        60.0    100147446  Beauty & Grooming           R-FSD-52352           300.0            cod     7/1/2016       Net     360   2016.0   7.0         2016-7  7-2016  FY17         4.0        None        None        None        None        None
4  211136.0  order_refunded   7/1/2016                                        BK7010400AG   555.0         2.0      1110.0    100147447            Soghaat                    \N             0.0            cod     7/1/2016     Valid   1,110   2016.0   7.0         2016-7  7-2016  FY17         5.0        None        None        None        None        None

📂 Tabel Hari Libur (raw_layer.holidays)
📊 STATISTIK DIMENSI:
   • Jumlah Baris : 60
   • Jumlah Kolom : 5

📋 DAFTAR SEMUA FITUR (KOLOM):
   ['adm_name', 'iso3', 'date', 'name', 'type']

👀 PREVIEW DATA (5 Baris Teratas):

   adm_name iso3        date            name        type
0  Pakistan  PAK  2016-09-06     Defence Day  Observance
1  Pakistan  PAK  2016-11-09       Iqbal Day  Observance
2  Pakistan  PAK  2016-12-24   Christmas Eve  Observance
3  Pakistan  PAK  2016-12-31  New Year's Eve  Observance
4  Pakistan  PAK  2017-04-16   Easter Sunday  Observance

# Transform

## Cleaning

In [10]:
# Cell 10
engine = create_engine('postgresql://postgres:bigdata@localhost:5432/ecommerce_db', echo=False)

def setup_staging():
    with engine.connect() as conn:
        conn.execute(text("CREATE SCHEMA IF NOT EXISTS warehouse_layer;"))

        conn.execute(text("DROP TABLE IF EXISTS warehouse_layer.staging_ecommerce;"))
        conn.execute(text("""
            CREATE TABLE warehouse_layer.staging_ecommerce AS
            SELECT * FROM raw_layer.ecommerce;
        """))

        conn.execute(text("DROP TABLE IF EXISTS warehouse_layer.staging_holidays;"))
        conn.execute(text("""
            CREATE TABLE warehouse_layer.staging_holidays AS
            SELECT * FROM raw_layer.holidays;
        """))

        conn.commit()

    row_count = pd.read_sql("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce", engine).iloc[0,0]
    print(f"✅ Tabel Staging Siap! Total Data Awal: {row_count} baris.")

setup_staging()

✅ Tabel Staging Siap! Total Data Awal: 1153432 baris.

### Source 1

#### Handling Duplicate Data

In [11]:
# Cell 11
def clean_duplicates_s1():
    print("Menghapus Data Duplikat...")

    sql_dedup = """
        DELETE FROM warehouse_layer.staging_ecommerce a
        USING warehouse_layer.staging_ecommerce b
        WHERE a.ctid < b.ctid  -- Hapus salah satu dari pasangan duplikat
          AND a.item_id = b.item_id
          AND a.created_at = b.created_at
          AND a.grand_total = b.grand_total;
    """

    with engine.connect() as conn:
        before = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce")).scalar()

        conn.execute(text(sql_dedup))
        conn.commit()

        after = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce")).scalar()

    print(f"✅ Duplikat Dihapus: {before - after} baris.")
    print(f"   Sisa Data: {after}")

clean_duplicates_s1()

Menghapus Data Duplikat...
✅ Duplikat Dihapus: 58589 baris.
   Sisa Data: 1094843

#### Handling Missing Value & Noise

In [12]:
# Cell 12
def clean_missing_s1():
    print("Menangani Missing Value & Data Sampah...")

    sql_missing = """
        DELETE FROM warehouse_layer.staging_ecommerce
        WHERE
            item_id IS NULL
            OR TRIM(item_id) = ''
            OR created_at NOT LIKE '%/%/%';
    """

    with engine.connect() as conn:
        before = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce")).scalar()
        conn.execute(text(sql_missing))
        conn.commit()
        after = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce")).scalar()

    print(f"✅ Data Sampah/Kosong Dihapus: {before - after} baris.")
    print(f"   Sisa Data Valid: {after}")

clean_missing_s1()

Menangani Missing Value & Data Sampah...
✅ Data Sampah/Kosong Dihapus: 510319 baris.
   Sisa Data Valid: 584524

#### Standarisasi String

In [13]:
# Cell 13
def standardize_string_s1():
    print("Standarisasi Teks (Lowercase & Trim)...")

    sql_std = """
        UPDATE warehouse_layer.staging_ecommerce
        SET
            status = LOWER(TRIM(status)),
            category_name_1 = LOWER(TRIM(category_name_1)),
            payment_method = LOWER(TRIM(payment_method));
    """

    with engine.connect() as conn:
        conn.execute(text(sql_std))
        conn.commit()

    print("✅ Teks berhasil distandarisasi.")
    df_sample = pd.read_sql("SELECT status, category_name_1, payment_method FROM warehouse_layer.staging_ecommerce LIMIT 3", engine)
    display(df_sample)

standardize_string_s1()

Standarisasi Teks (Lowercase & Trim)...
✅ Teks berhasil distandarisasi.

     status    category_name_1 payment_method
0  canceled  beauty & grooming            cod
1  canceled    women's fashion            cod
2  complete  beauty & grooming            cod

#### Cleaning Format Angka & Tanggal

In [14]:
# Cell 14
def clean_numeric_date_s1():
    print("Membersihkan Format Angka (Hapus Koma) & Tanggal...")

    sql_fix_formats = """
    UPDATE warehouse_layer.staging_ecommerce
    SET
        qty_ordered = REGEXP_REPLACE(qty_ordered, '[^0-9.-]', '', 'g'),
        price = REGEXP_REPLACE(price, '[^0-9.-]', '', 'g'),
        grand_total = REGEXP_REPLACE(grand_total, '[^0-9.-]', '', 'g'),
        discount_amount = REGEXP_REPLACE(discount_amount, '[^0-9.-]', '', 'g');

    ALTER TABLE warehouse_layer.staging_ecommerce
    ALTER COLUMN qty_ordered TYPE INTEGER USING qty_ordered::NUMERIC::INTEGER,

    ALTER COLUMN price TYPE NUMERIC USING price::NUMERIC,
    ALTER COLUMN grand_total TYPE NUMERIC USING grand_total::NUMERIC,
    ALTER COLUMN discount_amount TYPE NUMERIC USING discount_amount::NUMERIC,

    ALTER COLUMN created_at TYPE DATE USING TO_DATE(created_at, 'M/D/YYYY');
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_fix_formats))
            conn.commit()
        print("✅ Konversi Tipe Data Sukses! (TEXT -> NUMERIC/DATE)")

        df_dtypes = pd.read_sql("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'staging_ecommerce' AND column_name IN ('price', 'created_at', 'qty_ordered')
        """, engine)
        display(df_dtypes)

    except Exception as e:
        print(f"❌ Gagal Convert Tipe Data: {e}")

clean_numeric_date_s1()

Membersihkan Format Angka (Hapus Koma) & Tanggal...
✅ Konversi Tipe Data Sukses! (TEXT -> NUMERIC/DATE)

   column_name data_type
0   created_at      date
1        price   numeric
2  qty_ordered   integer

#### Handling Outliers

In [15]:
def clean_outliers_s1():
    print("Menghapus Outliers (Harga/Qty Negatif & Tanggal Error)...")

    sql_outlier = """
        DELETE FROM warehouse_layer.staging_ecommerce
        WHERE
            price <= 0
            OR qty_ordered <= 0
            OR created_at < '2000-01-01';
    """

    with engine.connect() as conn:
        before = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce")).scalar()
        conn.execute(text(sql_outlier))
        conn.commit()
        after = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_ecommerce")).scalar()

    print(f"✅ Outliers & Data Sampah Dihapus: {before - after} baris.")
    print(f"   Total Data Bersih Akhir Source 1: {after}")

clean_outliers_s1()

Menghapus Outliers (Harga/Qty Negatif & Tanggal Error)...
✅ Outliers & Data Sampah Dihapus: 216937 baris.
   Total Data Bersih Akhir Source 1: 367587

### Source 2

#### Handling Duplicate

In [16]:
# Cell 16
def clean_duplicates_s2():
    print("Menghapus Data Duplikat...")

    sql_dedup = """
        DELETE FROM warehouse_layer.staging_holidays a
        USING warehouse_layer.staging_holidays b
        WHERE a.ctid < b.ctid
          AND a.date = b.date
          AND a.name = b.name;
    """

    try:
        with engine.connect() as conn:
            before = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_holidays")).scalar()
            conn.execute(text(sql_dedup))
            conn.commit()
            after = conn.execute(text("SELECT COUNT(*) FROM warehouse_layer.staging_holidays")).scalar()

        print(f"✅ Duplikat Source 2 Dihapus: {before - after} baris.")
        print(f"   Sisa Data: {after}")
    except Exception as e:
        print(f"❌ Gagal Dedup Source 2: {e}")

clean_duplicates_s2()

Menghapus Data Duplikat...
✅ Duplikat Source 2 Dihapus: 0 baris.
   Sisa Data: 60

#### Standarisasi Rename fitur

In [17]:
# Cell 17
def rename_columns_s2():
    print("Menyeragamkan Nama Kolom...")

    sql_rename = """
        ALTER TABLE warehouse_layer.staging_holidays
        RENAME COLUMN date TO date_holiday;

        ALTER TABLE warehouse_layer.staging_holidays
        RENAME COLUMN name TO holiday_name;

        ALTER TABLE warehouse_layer.staging_holidays
        RENAME COLUMN type TO holiday_type;
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_rename))
            conn.commit()
        print("✅ Kolom berhasil di-rename (date -> date_holiday, dll).")

        df_cols = pd.read_sql("SELECT * FROM warehouse_layer.staging_holidays LIMIT 1", engine)
        print(f"   Kolom Sekarang: {list(df_cols.columns)}")

    except Exception as e:
        print(f"⚠️ Info Rename: {e}")

rename_columns_s2()

Menyeragamkan Nama Kolom...
✅ Kolom berhasil di-rename (date -> date_holiday, dll).
   Kolom Sekarang: ['adm_name', 'iso3', 'date_holiday', 'holiday_name', 'holiday_type']

#### Ubah Tipe Data

In [18]:
# Cell 18
def convert_type_s2():
    print("Mengubah Tipe Data (TEXT -> DATE)...")

    sql_type = """
        ALTER TABLE warehouse_layer.staging_holidays
        ALTER COLUMN date_holiday TYPE DATE USING TO_DATE(date_holiday, 'YYYY-MM-DD');
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_type))
            conn.commit()
        print("✅ Tipe Data Tanggal Berhasil Diubah.")
    except Exception as e:
        print(f"❌ Gagal Ubah Tipe Source 2: {e}")

convert_type_s2()

Mengubah Tipe Data (TEXT -> DATE)...
✅ Tipe Data Tanggal Berhasil Diubah.

## Standarisasi

#### Encoding Kategorikal

In [19]:
# Cell 19

# Setup Koneksi Global
engine = create_engine('postgresql://postgres:bigdata@localhost:5432/ecommerce_db', echo=False)

def standardization_encoding():
    print("Pre-processing Melakukan Encoding Kategorikal...")

    sql_add_cols = """
        ALTER TABLE warehouse_layer.staging_ecommerce
        ADD COLUMN IF NOT EXISTS payment_id INTEGER,
        ADD COLUMN IF NOT EXISTS status_id INTEGER;
    """

    sql_encode = """
        UPDATE warehouse_layer.staging_ecommerce
        SET
            payment_id = CASE
                WHEN payment_method IN ('cod', 'cash_on_delivery') THEN 1
                WHEN payment_method LIKE '%bank%' THEN 2
                WHEN payment_method LIKE '%card%' THEN 3
                WHEN payment_method LIKE '%easypaisa%' THEN 4
                WHEN payment_method LIKE '%jazz%' THEN 5
                ELSE 0
            END,

            status_id = CASE
                WHEN status = 'complete' THEN 1
                WHEN status IN ('canceled', 'cancelled') THEN 2
                WHEN status = 'received' THEN 3
                WHEN status = 'refund' THEN 4
                ELSE 0
            END;
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_add_cols))
            conn.execute(text(sql_encode))
            conn.commit()

        print("✅ Encoding Selesai! Kolom 'payment_id' dan 'status_id' berhasil dibuat.")

        df_enc = pd.read_sql("SELECT payment_method, payment_id, status, status_id FROM warehouse_layer.staging_ecommerce LIMIT 5", engine)
        display(df_enc)

    except Exception as e:
        print(f"❌ Error Encoding: {e}")

standardization_encoding()

Pre-processing Melakukan Encoding Kategorikal...
✅ Encoding Selesai! Kolom 'payment_id' dan 'status_id' berhasil dibuat.

  payment_method  payment_id    status  status_id
0            cod           1  complete          1
1            cod           1  complete          1
2            cod           1  complete          1
3            cod           1  complete          1
4            cod           1  complete          1

### Normalisasi

In [20]:
# Cell 20
def standardization_normalization():
    print("Pre-processing Melakukan Normalisasi Numerik (0-1)...")

    sql_add_norm = """
        ALTER TABLE warehouse_layer.staging_ecommerce
        ADD COLUMN IF NOT EXISTS qty_norm NUMERIC,
        ADD COLUMN IF NOT EXISTS total_norm NUMERIC;
    """

    sql_normalize = """
        WITH stats AS (
            SELECT
                MIN(qty_ordered) as min_q, MAX(qty_ordered) as max_q,
                MIN(grand_total) as min_t, MAX(grand_total) as max_t
            FROM warehouse_layer.staging_ecommerce
        )
        UPDATE warehouse_layer.staging_ecommerce
        SET
            qty_norm = ROUND( (qty_ordered - (SELECT min_q FROM stats))::NUMERIC / NULLIF((SELECT max_q - min_q FROM stats), 0), 4),
            total_norm = ROUND( (grand_total - (SELECT min_t FROM stats))::NUMERIC / NULLIF((SELECT max_t - min_t FROM stats), 0), 4);
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_add_norm))
            conn.execute(text(sql_normalize))
            conn.commit()

        print("✅ Normalisasi Selesai! Kolom 'qty_norm' dan 'total_norm' berhasil dibuat.")

        df_norm = pd.read_sql("SELECT qty_ordered, qty_norm, grand_total, total_norm FROM warehouse_layer.staging_ecommerce LIMIT 5", engine)
        display(df_norm)

    except Exception as e:
        print(f"❌ Error Normalisasi: {e}")

standardization_normalization()

Pre-processing Melakukan Normalisasi Numerik (0-1)...
✅ Normalisasi Selesai! Kolom 'qty_norm' dan 'total_norm' berhasil dibuat.

   qty_ordered  qty_norm  grand_total  total_norm
0            1       0.0        325.0      0.0001
1            1       0.0        399.0      0.0001
2            1       0.0        799.0      0.0001
3            1       0.0        275.0      0.0001
4            1       0.0        499.0      0.0001

## Data Enrichment

In [21]:
# Cell 21
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine('postgresql://postgres:bigdata@localhost:5432/ecommerce_db', echo=False)

def step_enrichment():
    print("Data Enrichment (Joining Source 1 & 2)")

    sql_enrich = """
    DROP TABLE IF EXISTS warehouse_layer.fact_sales_enriched;

    CREATE TABLE warehouse_layer.fact_sales_enriched AS
    SELECT

        e.*,

        h.holiday_name,
        h.holiday_type,

        CASE WHEN h.date_holiday IS NOT NULL THEN 1 ELSE 0 END AS is_holiday

    FROM warehouse_layer.staging_ecommerce e
    LEFT JOIN warehouse_layer.staging_holidays h
        ON e.created_at = h.date_holiday;
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_enrich))
            conn.commit()

        print("✅ Data Enrichment Berhasil!")
        print("   Tabel 'warehouse_layer.fact_sales_enriched' telah dibuat.")

        chk = pd.read_sql("""
            SELECT created_at, holiday_name, is_holiday
            FROM warehouse_layer.fact_sales_enriched
            WHERE is_holiday = 1 LIMIT 3
        """, engine)
        print("   👀 Sampel Data Libur (Bukti Join Sukses):")
        display(chk)

    except Exception as e:
        print(f"❌ Error Enrichment: {e}")

step_enrichment()

Data Enrichment (Joining Source 1 & 2)
✅ Data Enrichment Berhasil!
   Tabel 'warehouse_layer.fact_sales_enriched' telah dibuat.
   👀 Sampel Data Libur (Bukti Join Sukses):

   created_at            holiday_name  is_holiday
0  2018-01-01  January 1 Bank Holiday           1
1  2018-01-01  January 1 Bank Holiday           1
2  2018-01-01  January 1 Bank Holiday           1

## Feature Engineering

In [22]:
# Cell 22
def step_feature_engineering():
    print("Feature Engineering & Analytical Metrics...")

    sql_feat = """
    DROP TABLE IF EXISTS warehouse_layer.fact_sales_final;

    CREATE TABLE warehouse_layer.fact_sales_final AS
    SELECT
        base.*,

        TRIM(TO_CHAR(base.created_at, 'Day')) AS day_name,
        CONCAT('Q', EXTRACT(QUARTER FROM base.created_at)) AS quarter_period,
        CASE WHEN EXTRACT(ISODOW FROM base.created_at) IN (6, 7) THEN TRUE ELSE FALSE END AS is_weekend,

        ROUND(base.discount_amount / NULLIF((base.price * base.qty_ordered), 0), 4) AS discount_ratio,

        SUM(base.grand_total) OVER (PARTITION BY base.customer_id ORDER BY base.created_at) AS customer_running_total,

        ROUND(AVG(base.grand_total) OVER (PARTITION BY base.category_name_1), 2) AS category_avg_sales,

        ROUND(
            base.grand_total / NULLIF(SUM(base.grand_total) OVER (PARTITION BY base.created_at), 0),
            6
        ) AS daily_contribution_pct

    FROM warehouse_layer.fact_sales_enriched base;
    """

    try:
        with engine.connect() as conn:
            conn.execute(text(sql_feat))
            conn.commit()

        print("✅ Feature Engineering Berhasil!")
        print("   Tabel Final 'warehouse_layer.fact_sales_final' siap.")

        print("\nSampel Fitur Analitik (Window Functions):")
        chk = pd.read_sql("""
            SELECT customer_id, created_at, grand_total,
                   customer_running_total, daily_contribution_pct
            FROM warehouse_layer.fact_sales_final
            ORDER BY customer_id, created_at
            LIMIT 5
        """, engine)
        display(chk)

    except Exception as e:
        print(f"❌ Error Feature Engineering: {e}")

step_feature_engineering()

Feature Engineering & Analytical Metrics...
✅ Feature Engineering Berhasil!
   Tabel Final 'warehouse_layer.fact_sales_final' siap.

Sampel Fitur Analitik (Window Functions):

  customer_id  created_at  grand_total  customer_running_total  daily_contribution_pct
0         1.0  2016-01-01       1950.0                  1950.0                0.000010
1        10.0  2016-01-01        366.0                   732.0                0.000002
2        10.0  2016-01-01        366.0                   732.0                0.000002
3       100.0  2016-01-01        999.0                  1998.0                0.000005
4       100.0  2016-01-01        999.0                  1998.0                0.000005

## Validasi Data

In [23]:
# Cell 23
def final_quality_check():
    print("Validasi Laporan Kualitas Data Akhir:\n")

    checks = [
        ("1. Uniqueness Check (Item ID)",
         "SELECT COUNT(item_id) - COUNT(DISTINCT item_id) FROM warehouse_layer.fact_sales_final"),

        ("2. Null Check (Primary Key & Date)",
         "SELECT COUNT(*) FROM warehouse_layer.fact_sales_final WHERE item_id IS NULL OR created_at IS NULL"),

        ("3️. Range Check (Kolom Normalisasi)",
         "SELECT COUNT(*) FROM warehouse_layer.fact_sales_final WHERE qty_norm < 0 OR qty_norm > 1"),

        ("4️. Datatype Consistency (Grand Total is Numeric?)",
         """SELECT CASE WHEN data_type = 'numeric' THEN 0 ELSE 1 END
            FROM information_schema.columns
            WHERE table_name = 'fact_sales_final' AND column_name = 'grand_total'"""),

        ("5️. Referential Integrity (Holiday Name Valid)",
         "SELECT COUNT(*) FROM warehouse_layer.fact_sales_final WHERE is_holiday = 1 AND holiday_name IS NULL")
    ]

    for title, query in checks:
        res = pd.read_sql(query, engine).iloc[0,0]
        status = "✅ PASS" if res == 0 else f"❌ FAIL ({res} issues)"
        print(f"{title}: {status}")

    # 6. Distribusi Data (Statistik)
    print("\n6️⃣ Distribusi Data (Grand Total Statistics):")
    sql_dist = """
        SELECT
            MIN(grand_total) as min_val,
            AVG(grand_total) as mean_val,
            MAX(grand_total) as max_val,
            STDDEV(grand_total) as std_dev
        FROM warehouse_layer.fact_sales_final;
    """
    display(pd.read_sql(sql_dist, engine))

final_quality_check()

Validasi Laporan Kualitas Data Akhir:

1. Uniqueness Check (Item ID): ✅ PASS
2. Null Check (Primary Key & Date): ✅ PASS
3️. Range Check (Kolom Normalisasi): ✅ PASS
4️. Datatype Consistency (Grand Total is Numeric?): ✅ PASS
5️. Referential Integrity (Holiday Name Valid): ✅ PASS

6️⃣ Distribusi Data (Grand Total Statistics):

   min_val     mean_val     max_val       std_dev
0  -1311.5  9595.435593  17888000.0  76533.494527

In [24]:
# Cell 24
def preview_warehouse_completeness():
    print("Preview Warehouse Layer:\n")

    sql_tables = """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'warehouse_layer'
        ORDER BY table_name;
    """
    tables = pd.read_sql(sql_tables, engine)['table_name'].tolist()

    for tbl in tables:
        full_name = f"warehouse_layer.{tbl}"
        print(f"📂 TABEL: {full_name}")
        print("="*60)

        try:
            rows = pd.read_sql(f"SELECT COUNT(*) FROM {full_name}", engine).iloc[0,0]
            cols = len(pd.read_sql(f"SELECT * FROM {full_name} LIMIT 0", engine).columns)

            print(f"📊 Dimensi: {rows} Baris x {cols} Kolom")

            print(f"👀 Sample Data (5 Baris):")
            df_sample = pd.read_sql(f"SELECT * FROM {full_name} LIMIT 5", engine)
            display(df_sample)
            print("\n")

        except Exception as e:
            print(f"❌ Error akses tabel: {e}\n")

preview_warehouse_completeness()

Preview Warehouse Layer:

📂 TABEL: warehouse_layer.fact_sales_enriched
============================================================
📊 Dimensi: 367587 Baris x 33 Kolom
👀 Sample Data (5 Baris):

    item_id    status  created_at                           sku    price  qty_ordered  grand_total increment_id    category_name_1 sales_commission_code  discount_amount payment_method working_date bi_status        mv    year month customer_since     m_y    fy customer_id unnamed__21 unnamed__22 unnamed__23 unnamed__24 unnamed__25  payment_id  status_id  qty_norm  total_norm holiday_name holiday_type  is_holiday
0  246187.0  complete  2016-01-01                 Anchor_449-XL    499.0            1       499.00    100171101      men's fashion                    \N             0.00            cod    9/28/2016       Net      499   2016.0   9.0         2016-8  9-2016  FY17      4349.0        None        None        None        None        None           1          1       0.0      0.0001         None         None           0
1  255114.0  canceled  2016-01-01  Apple iPhone 6 (64GB) Silver  70567.0            1     59981.95    100177682  mobiles & tablets                    \N         10585.05        payaxis    9/30/2016     Gross   70,567   2016.0   9.0         2016-9  9-2016  FY17     10245.0        None        None        None        None        None           0          2       0.0      0.0034         None         None           0
2  255121.0  complete  2016-01-01        BO_shovel-truck-orange    290.0            1       290.00    100177687        kids & baby                    \N             0.00            cod    9/30/2016       Net      290   2016.0   9.0         2016-9  9-2016  FY17      9588.0        None        None        None        None        None           1          1       0.0      0.0001         None         None           0
3  255124.0  canceled  2016-01-01       Apple iPhone 5S (16 GB)  35555.0            1     24888.50    100177690  mobiles & tablets                    \N         10666.50        payaxis    9/30/2016     Gross   35,555   2016.0   9.0         2016-9  9-2016  FY17     10245.0        None        None        None        None        None           0          2       0.0      0.0015         None         None           0
4  255125.0  complete  2016-01-01                    emart_00-1    649.0            1       324.50    100177691                 \n                    \N           324.50        payaxis    9/30/2016       Net      649   2016.0   9.0         2016-9  9-2016  FY17      7653.0        None        None        None        None        None           0          1       0.0      0.0001         None         None           0

📂 TABEL: warehouse_layer.fact_sales_final
============================================================
📊 Dimensi: 367587 Baris x 40 Kolom
👀 Sample Data (5 Baris):

    item_id    status  created_at                         sku   price  qty_ordered  grand_total increment_id    category_name_1 sales_commission_code  discount_amount payment_method working_date bi_status       mv    year month customer_since     m_y    fy customer_id unnamed__21 unnamed__22 unnamed__23 unnamed__24 unnamed__25  payment_id  status_id  qty_norm  total_norm holiday_name holiday_type  is_holiday day_name quarter_period  is_weekend  discount_ratio  customer_running_total  category_avg_sales  daily_contribution_pct
0  254054.0  complete  2016-01-01     kcc_Cool Pocket Perfume   120.0            1        698.0    100176846  beauty & grooming                    \N              0.0            cod    9/30/2016       Net     120   2016.0   9.0         2016-9  9-2016  FY17      8982.0        None        None        None        None        None           1          1       0.0      0.0001         None         None           0   Friday             Q1       False             0.0                  3791.0             2443.47                0.000004
1  249090.0  complete  2016-01-01  RS_Sohan Halwa_Tin-1000 GM   640.0            1        965.0    100173379            soghaat                    \N              0.0            cod    9/29/2016       Net     640   2016.0   9.0         2016-9  9-2016  FY17      8970.0        None        None        None        None        None           1          1       0.0      0.0001         None         None           0   Friday             Q1       False             0.0                  1930.0             1562.91                0.000005
2  249210.0  complete  2016-01-01  interwood_HF-12CR-HW-11284  7371.0            1       7371.0    100173468      home & living                    \N              0.0            cod    9/29/2016       Net   7,371   2016.0   9.0         2016-9  9-2016  FY17      8987.0        None        None        None        None        None           1          1       0.0      0.0005         None         None           0   Friday             Q1       False             0.0                  7371.0             3207.69                0.000039
3  249092.0  complete  2016-01-01    RS_Honey Dry Fruit Halwa   325.0            1        965.0    100173379            soghaat                    \N              0.0            cod    9/29/2016       Net     325   2016.0   9.0         2016-9  9-2016  FY17      8970.0        None        None        None        None        None           1          1       0.0      0.0001         None         None           0   Friday             Q1       False             0.0                  1930.0             1562.91                0.000005
4  253746.0  complete  2016-01-01         RB_Household Bundle   999.0            1        799.2    100176610         superstore                    \N            199.8        payaxis    9/30/2016       Net     999   2016.0   9.0         2016-9  9-2016  FY17      8887.0        None        None        None        None        None           0          1       0.0      0.0001         None         None           0   Friday             Q1       False             0.2                 10659.2             2742.27                0.000004

📂 TABEL: warehouse_layer.staging_ecommerce
============================================================
📊 Dimensi: 367587 Baris x 30 Kolom
👀 Sample Data (5 Baris):

    item_id    status  created_at                           sku    price  qty_ordered  grand_total increment_id    category_name_1 sales_commission_code  discount_amount payment_method working_date bi_status        mv    year month customer_since     m_y    fy customer_id unnamed__21 unnamed__22 unnamed__23 unnamed__24 unnamed__25  payment_id  status_id  qty_norm  total_norm
0  246187.0  complete  2016-01-01                 Anchor_449-XL    499.0            1       499.00    100171101      men's fashion                    \N             0.00            cod    9/28/2016       Net      499   2016.0   9.0         2016-8  9-2016  FY17      4349.0        None        None        None        None        None           1          1       0.0      0.0001
1  255114.0  canceled  2016-01-01  Apple iPhone 6 (64GB) Silver  70567.0            1     59981.95    100177682  mobiles & tablets                    \N         10585.05        payaxis    9/30/2016     Gross   70,567   2016.0   9.0         2016-9  9-2016  FY17     10245.0        None        None        None        None        None           0          2       0.0      0.0034
2  255121.0  complete  2016-01-01        BO_shovel-truck-orange    290.0            1       290.00    100177687        kids & baby                    \N             0.00            cod    9/30/2016       Net      290   2016.0   9.0         2016-9  9-2016  FY17      9588.0        None        None        None        None        None           1          1       0.0      0.0001
3  255124.0  canceled  2016-01-01       Apple iPhone 5S (16 GB)  35555.0            1     24888.50    100177690  mobiles & tablets                    \N         10666.50        payaxis    9/30/2016     Gross   35,555   2016.0   9.0         2016-9  9-2016  FY17     10245.0        None        None        None        None        None           0          2       0.0      0.0015
4  255125.0  complete  2016-01-01                    emart_00-1    649.0            1       324.50    100177691                 \n                    \N           324.50        payaxis    9/30/2016       Net      649   2016.0   9.0         2016-9  9-2016  FY17      7653.0        None        None        None        None        None           0          1       0.0      0.0001

📂 TABEL: warehouse_layer.staging_holidays
============================================================
📊 Dimensi: 60 Baris x 5 Kolom
👀 Sample Data (5 Baris):

   adm_name iso3 date_holiday    holiday_name holiday_type
0  Pakistan  PAK   2016-09-06     Defence Day   Observance
1  Pakistan  PAK   2016-11-09       Iqbal Day   Observance
2  Pakistan  PAK   2016-12-24   Christmas Eve   Observance
3  Pakistan  PAK   2016-12-31  New Year's Eve   Observance
4  Pakistan  PAK   2017-04-16   Easter Sunday   Observance

# Visualisasi

In [25]:
engine = create_engine('postgresql://postgres:bigdata@localhost:5432/ecommerce_db', echo=False)

def generate_dashboard_final():
    print("Mengambil data bersih dari Warehouse...")

    query = """
    SELECT
        created_at,
        category_name_1,
        payment_method,
        grand_total,
        qty_ordered,
        is_holiday,
        holiday_name,
        status
    FROM warehouse_layer.fact_sales_final
    ORDER BY created_at;
    """

    try:
        df = pd.read_sql(query, engine)

        df = df.rename(columns={
            'created_at': 'order_date',
            'category_name_1': 'category',
            'status': 'status_original'
        })

        df['order_date'] = pd.to_datetime(df['order_date'])
        df['month_year'] = df['order_date'].dt.to_period('M').astype(str)

        print(f"✅ Data Loaded: {len(df)} baris valid.")

        total_revenue = df['grand_total'].sum()
        total_orders = df['qty_ordered'].sum()
        avg_order_value = df['grand_total'].mean()

        holiday_rev = df[df['is_holiday']==1]['grand_total'].sum()
        holiday_sales_pct = (holiday_rev / total_revenue) * 100 if total_revenue > 0 else 0

        print(f"\n--- 🚀 E-COMMERCE EXECUTIVE SUMMARY ---")
        print(f"💰 Total Revenue      : PKR {total_revenue:,.0f}")
        print(f"📦 Total Orders       : {total_orders:,.0f}")
        print(f"🛒 Avg Order Value    : PKR {avg_order_value:,.2f}")
        print(f"🎉 Holiday Sales Contrib : {holiday_sales_pct:.2f}%")
        print("-" * 50)


        cat_sales = df.groupby('category')['grand_total'].sum().reset_index().sort_values('grand_total', ascending=False)
        fig2 = px.bar(cat_sales, x='category', y='grand_total', color='grand_total',
                      title='<b>📊 Pendapatan per Kategori Produk</b>',
                      color_continuous_scale='Viridis')
        fig2.show()

        fig3 = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'xy'}]],
                             subplot_titles=['<b>Metode Pembayaran</b>', '<b>Dampak Liburan (Distribusi)</b>'])

        # A. Pie Chart
        pay_counts = df['payment_method'].value_counts().reset_index().head(5)
        fig3.add_trace(go.Pie(labels=pay_counts.iloc[:,0], values=pay_counts.iloc[:,1], name="Payment"),
                       row=1, col=1)

        # B. Box Plot (Sample data agar ringan)
        sample_limit = min(5000, len(df))
        sample_df = df.sample(n=sample_limit, random_state=42)

        fig3.add_trace(go.Box(x=sample_df['is_holiday'].map({0: 'Normal Day', 1: 'Holiday'}),
                              y=sample_df['grand_total'], name="Sales Distrib"),
                       row=1, col=2)

        fig3.update_layout(title_text="<b>🔎 Analisis Pembayaran & Dampak Hari Libur</b>")
        fig3.show()

    except Exception as e:
        print(f"❌ Dashboard Error: {e}")

generate_dashboard_final()

Mengambil data bersih dari Warehouse...
✅ Data Loaded: 367587 baris valid.

--- 🚀 E-COMMERCE EXECUTIVE SUMMARY ---
💰 Total Revenue      : PKR 3,527,157,383
📦 Total Orders       : 509,257
🛒 Avg Order Value    : PKR 9,595.44
🎉 Holiday Sales Contrib : 59.34%
--------------------------------------------------

In [26]:
def generate_dashboard_storytelling():
    print("📊 Mengambil data dan menyiapkan Storytelling Dashboard...")

    query = """
    SELECT
        created_at,
        category_name_1,
        grand_total,
        qty_ordered,

        -- Fitur Enrichment
        is_holiday,
        holiday_name,

        -- Fitur Engineering
        day_name,
        quarter_period,
        discount_ratio,
        status,
        payment_method
    FROM warehouse_layer.fact_sales_final
    WHERE grand_total > 0
    ORDER BY created_at;
    """

    try:
        df = pd.read_sql(query, engine)

        # Rename kolom untuk tampilan
        df = df.rename(columns={
            'created_at': 'order_date',
            'category_name_1': 'category',
            'status': 'status_original'
        })

        # Konversi Date & Buat Month-Year
        df['order_date'] = pd.to_datetime(df['order_date'])
        df['month_year'] = df['order_date'].dt.to_period('M').astype(str)

        # Urutan Hari agar grafik rapi (Senin - Minggu)
        days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        df['day_name'] = pd.Categorical(df['day_name'], categories=days_order, ordered=True)

        print(f"✅ Data Siap: {len(df)} transaksi.")
        print("-" * 60)

        # STORY 2: PERILAKU PELANGGAN (Menjawab: Day Name & Holiday)
        fig3 = make_subplots(rows=1, cols=2,
                             subplot_titles=['<b>Pola Belanja Mingguan (Day Name)</b>',
                                             '<b>Dampak Liburan vs Biasa (Enrichment)</b>'])

        # A. Pola Mingguan (Menjawab Feature: day_name)
        day_sales = df.groupby('day_name')['grand_total'].mean().reset_index()
        fig3.add_trace(go.Bar(x=day_sales['day_name'], y=day_sales['grand_total'],
                              name="Avg Sales", marker_color='teal'), row=1, col=1)

        # B. Dampak Liburan (Menjawab Enrichment: is_holiday)
        hol_sales = df.groupby('is_holiday')['grand_total'].mean().reset_index()
        hol_sales['label'] = hol_sales['is_holiday'].map({0: 'Hari Biasa', 1: 'Libur Nasional'})

        fig3.add_trace(go.Bar(x=hol_sales['label'], y=hol_sales['grand_total'],
                              name="Holiday Impact", marker_color=['gray', 'orange']), row=1, col=2)

        fig3.update_layout(title_text="<b>📅 3. Analisis Perilaku: Kapan Orang Belanja?</b>")
        fig3.show()

        cat_status = df.groupby(['category', 'status_original'])['grand_total'].count().reset_index()

        fig5 = px.bar(cat_status, x='category', y='grand_total', color='status_original',
                      title='<b>🚦 5. Status Pesanan per Kategori (Interactive Filter)</b>',
                      labels={'grand_total': 'Jumlah Transaksi'})

        status_list = list(df['status_original'].unique())
        buttons = [dict(label="All Status", method="restyle", args=[{"visible": [True] * len(status_list)}])]

        for stat in ['complete', 'canceled', 'refund']:
            pass

        fig5.update_layout(legend_title="Klik Legend untuk Filter ->")
        fig5.show()

    except Exception as e:
        print(f"❌ Dashboard Error: {e}")

generate_dashboard_storytelling()

📊 Mengambil data dan menyiapkan Storytelling Dashboard...
✅ Data Siap: 360157 transaksi.
------------------------------------------------------------

/tmp/ipython-input-1217974824.py:53: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.